import type { Metadata } from "next";
import "boxicons/css/boxicons.min.css";
import "./globals.css";
import { Poppins } from "next/font/google";
import SessionProvider from "@/components/sessionprovider/SessionProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import { ToasterProvider } from "@/components/common/ToasterWrapper";
import Providers from "./Profiders";

const popinsSans = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={` ${popinsSans.className} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
